apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
  namespace: kaushiksen1984-dev
spec:
  selector:
    app: kafka-producer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080